# Generated by Django 6.0.1 on 2026-03-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('investment_type', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Cryptocurrency'), ('real_estate', 'Real Estate'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('etf', 'ETF'), ('gold', 'Gold'), ('other', 'Other')], default='stocks', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
